Use Fetchcontent instead of ExternalProject
google/googletest pull request #3314
Opened 2021-03-13 15:59 UTC by Vollstrecker

Hi,

instead of ExternalProject and a new file that is spawned in a new process, it's easier to just use FetchContent. cmake 3.14 should be old enough to be spread.

2021-04-14 00:05 UTC, ericschmidtatwork requested changes
Thank you for this pull request! This update goes well with our new [CMake Quickstart](https://google.github.io/googletest/quickstart-cmake.html).

2021-04-14 11:45 UTC, Vollstrecker commented on googletest/README.md
>      is just a little more complex, but doesn't have the limitations of the other
Whatever make you happy.

2021-04-14 11:45 UTC, Vollstrecker commented on googletest/README.md
> +the code is pulled into the main build.
"small piece of CMake" would be sufficient, I think. Or CMake script.

2021-04-14 11:45 UTC, Vollstrecker commented on googletest/README.md
> -set(gtest_force_shared_crt ON CACHE BOOL "" FORCE)
GIT_REPOSITORY https://github.com/google/googletest.git
GIT_TAG release-1.10.0

2021-04-14 11:51 UTC, Vollstrecker commented on googletest/README.md
> -set(gtest_force_shared_crt ON CACHE BOOL "" FORCE)
For the shared_crt: Starting with cmake-3.15 [MSVC_RUNTIME_LIBRARY](https://cmake.org/cmake/help/latest/prop_tgt/MSVC_RUNTIME_LIBRARY.html) is available and solves this way more elegant.

2021-04-14 13:06 UTC, Vollstrecker commented
As the requested changes tab only listed the part with the 2 code, I changed only that one for now. I thought shortly about adding the GIT_TAG, but in the old example there was GIT_TAG master, which basically is the default, but also is the opposite of advising to stick to a version.

For adding the shared_crt, I'm unsure where, as the chapter where it was at the end of isn't there anymore. If you have any idea on that, just let me know, I hadn't any trouble with this atm on Win, Linux and Mac, but I usually use CmDaB for this task with is (not very well atm) documented [here](https://github.com/Vollstrecker/CmDaB), but I don't think your docs are the right place to promote that.

2021-04-14 19:58 UTC, dotam99 commented
- [ ]

2021-04-20 08:12 UTC, Vollstrecker commented on googletest/README.md
> +  GIT_REPOSITORY https://github.com/google/googletest.git
Sure, make sense if users should stick with a specific version. For myself, I prefer the git, diskspace isn't that big problems nowadays and I like to see if something breaks as early as possible.

2021-04-21 00:04 UTC, ericschmidtatwork approved these changes
Thanks, this looks good to me! We've pulled this in for internal review. Please don't push any more changes to this PR as they might be overwritten.
(369506093)

2021-04-21 14:24 UTC, merged