Fixed Grammer in Readme
google/googletest pull request #3490
Opened 2021-07-18 19:02 UTC by the-rebooted-coder

2021-07-18 19:24 UTC, the-rebooted-coder commented
@googlebot I signed it!

2021-07-28 20:00 UTC, derekmauro requested changes

2021-07-28 20:00 UTC, derekmauro commented on README.md
> +*   A [xUnit](https://en.wikipedia.org/wiki/XUnit) test framework.
I don't think this change is correct. "An" is used when a word begins with a vowel sound, and here is begins with an "ex" sound. Think "an xray".

2021-07-28 20:00 UTC, derekmauro commented on README.md
> +*   The [Chromium projects](http://www.chromium.org/) (behind the Chrome browser and Chrome OS).
This appears to be a whitespace only change. Please revert.

2021-07-28 20:00 UTC, derekmauro commented on README.md
> +*   [Protocol Buffers](https://github.com/google/protobuf), Google's data interchange format.
This appears to be a whitespace only change. Please revert.

2021-09-16 15:26 UTC, closed without merging