[gmock] Rename struct Result to avoid shadowing
google/googletest pull request #4221
Opened 2023-04-18 16:03 UTC by TurboGawron

Struct Result shadows global definition of class Result in gmock-spec-builders_test.cc inside ExpectCallTest.NonMoveableType test

2023-04-19 07:22 UTC, ankit-gautam23 requested changes
Changing just the case won't help much. We can think of some better name.

2023-04-20 08:26 UTC, TurboGawron commented
@ankit-gautam23  I agree, so maybe let's change that struct name to something to one of this: NonMoveableType, NonMoveableStruct, NonMoveableData, NonMoveableTestData or just NonMoveable. Or perhaps you have diffrent proposition? 
Sorry I dind't respond yesterday I was short on time after my work

2023-04-20 08:30 UTC, ankit-gautam23 commented
@TurboGawron Its truly okay. I will update this and raise the PR. Will add you as a reviewer. Thanks

2023-04-24 23:16 UTC, TurboGawron commented on googlemock/test/gmock-spec-builders_test.cc
> +  struct result {
Ok

2023-04-24 23:39 UTC, closed without merging